sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  matrix:
    - WTFORMS=2.0
cache:
  directories:
    - $HOME/.cache/pip
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install SQLAlchemy~=$ALCHEMY
  - python setup.py install
script: python runtests.py
